### ISSUE TITLE
[feature request] Add support other proxying applications

### ISSUE THREAD

**Issue by wendig0x** [Dr4tez/sing-box4asus#2]
Maybe you should add support for other proxying applications, like xray-core? It seems to me that changes to the script should be minimal for this.

**Comment by Dr4tez** [comment]
I am completely unfamiliar with xray. For now I am satisfied with the capabilities of sing-box and I do not plan to study xray and add its support to the script. Besides, I do not have time for this. If circumstances change in the future, I will consider your offer.
