### ISSUE TITLE
Странное поведение роутера с запущенным sbs

### ISSUE THREAD

**Issue by ef1f** [Dr4tez/sing-box4asus#3]
1 скорость падает до 200мб/с с запущенным sbs на сайтах, которые не должны заворачиваться в VPN. Загрузка CPU роутера примерно 60%
2 некоторые сайты не открываются и падают по таймауту, например личный кабинет налогоплательщика https://lkfl2.nalog.ru/lkfl, сам nalog.ru открывается нормально.

роутер ASUS RT-AX88U c последней прошивкой мерлина и развернутой entware, конфиг ваш с минимальными правками для своего VPS.

**Comment by Dr4tez** [comment]
А не надо всё подряд через sing-box пускать. Ограничения скорости через sing-box на наших роутерах не избежать, какое оно будет, зависит от производительности железа роутера, ядро sing-box не оптимизировано для роутеров, по крайней мере для асусов. Ограничение будет даже если трафик на сайт правилами конфига пускается в директ. Не хотите ограничений скорости на устройстве- не пускайте трафик этого устройства через sing-box.
Хотите без проблем попадать на сайты всяких Российских сервисов, особенно государственных, не пускайте весь трафик через прокси, пускайте только избранные домены, а остальное в директ. Или ищите все домены нужных Российских сервисов и пускайте их правилами конфига в директ. Некоторые сервисы даже не резолвятся некоторыми зарубежными днс серверами, это тоже имейте в виду.
